version: '3.2'
services:
  app:
    build:
      dockerfile: app/Dockerfile
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 api.routes:app --reload
    networks:
      - network
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    networks:
      - network
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db -U admin" ]
      interval: 1s
      timeout: 5s
      retries: 5
networks:
  network:
