version: '3.2'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - network
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
networks:
  network: