version: '3.2'
services:
  test_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    networks:
      - network
    ports:
      - '5431:5432'
    volumes:
      - ./test_db/:/var/lib/postgresql/data
networks:
  network:
